'use client';
import Link from 'next/link';
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { supabase } from '@/lib/supabase';
import '../platform.css';

type Project={id:string;name:string}; type Existing={id:string;name:string;normalized_name:string|null;location_code:string|null;location_category:string|null};
type Preview={rowNumber:number;sheet:string;name:string;originalName:string;normalized:string;category:string;status:'new'|'exact'|'similar'|'invalid';matched?:Existing;action:'create'|'link'|'skip';raw:Record<string,unknown>};
const CATEGORY_MAP:Record<string,string>={'الحدائق المنسقة':'الحدائق المنسقة','حدائق منسقة':'الحدائق المنسقة','الحدائق التقليدية':'الحدائق التقليدية','حدائق تقليدية':'الحدائق التقليدية','الزوائد':'الزوائد','زوائد':'الزوائد','الميادين':'الميادين','ميادين':'الميادين','الشوارع':'الشوارع','شوارع':'الشوارع'};
function norm(v:unknown){return String(v??'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim()}
function similarity(a:string,b:string){if(!a||!b)return 0;if(a===b)return 1;const x=a.replace(/\s/g,''),y=b.replace(/\s/g,'');const A=new Set([...Array(Math.max(0,x.length-1))].map((_,i)=>x.slice(i,i+2))),B=new Set([...Array(Math.max(0,y.length-1))].map((_,i)=>y.slice(i,i+2)));let n=0;A.forEach(v=>{if(B.has(v))n++});return A.size+B.size?2*n/(A.size+B.size):0}
function cleanName(value:string){return value.trim().replace(/\s+/g,' ').replace(/([^\d\s])(\d+)$/u,'$1 $2')}
function parseWorkbook(workbook:XLSX.WorkBook){const parsed:{sheet:string;rowNumber:number;name:string;category:string;raw:Record<string,unknown>}[]=[];workbook.SheetNames.forEach(sheetName=>{const matrix=XLSX.utils.sheet_to_json<any[]>(workbook.Sheets[sheetName],{header:1,defval:''});let category=sheetName.includes('الغابة')?'زون':'غير مصنف';matrix.forEach((cells,index)=>{const values=cells.map(v=>String(v??'').trim()).filter(Boolean);if(!values.length)return;const last=values[values.length-1];const categoryHit=CATEGORY_MAP[last];if(categoryHit){category=categoryHit;return}if(last==='اسم الموقع'){category='زون';return}if(last==='م'||last==='الرقم')return;const hasNumber=cells.some(v=>typeof v==='number'||/^\d+$/.test(String(v).trim()));if(hasNumber&&last&&!/^\d+$/.test(last))parsed.push({sheet:sheetName,rowNumber:index+1,name:cleanName(last),category,raw:{cells,original_name:last}})});});return parsed}
export default function ImportCenter(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[fileName,setFileName]=useState(''),[source,setSource]=useState<ReturnType<typeof parseWorkbook>>([]),[preview,setPreview]=useState<Preview[]>([]),[step,setStep]=useState(1),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[draftId,setDraftId]=useState(''),[batches,setBatches]=useState<any[]>([]);
 useEffect(()=>{void load()},[]); async function load(){const [p,b]=await Promise.all([supabase.from('projects').select('id,name').order('name'),supabase.from('location_import_batches').select('id,file_name,status,total_rows,created_at,projects(name),summary').order('created_at',{ascending:false}).limit(10)]);setProjects(p.data||[]);setBatches(b.data||[])}
 async function handleFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setLoading(true);setMessage('');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const rows=parseWorkbook(wb);setFileName(file.name);setSource(rows);setPreview([]);setStep(2);if(!rows.length)setMessage('لم أجد مواقع قابلة للقراءة في الملف.')}catch{setMessage('تعذر قراءة الملف.')}finally{setLoading(false)}}
 async function analyze(){if(!projectId||!source.length)return setMessage('اختر المشروع وارفع ملفًا صالحًا.');setLoading(true);const {data,error}=await supabase.from('locations').select('id,name,normalized_name,location_code,location_category').eq('project_id',projectId);if(error){setLoading(false);return setMessage(error.message)}const existing=(data||[]) as Existing[];const rows=source.map((r):Preview=>{const normalized=norm(r.name);const exact=existing.find(x=>(x.normalized_name||norm(x.name))===normalized&&(!x.location_category||x.location_category===r.category));let matched=exact,best=0;if(!exact)existing.forEach(x=>{if(x.location_category&&x.location_category!==r.category)return;const score=similarity(normalized,x.normalized_name||norm(x.name));if(score>best){best=score;matched=x}});const status=!r.name?'invalid':exact?'exact':best>=.78?'similar':'new';return{...r,originalName:String(r.raw.original_name||r.name),normalized,status,matched,action:status==='new'?'create':status==='invalid'?'skip':'link'}});setPreview(rows);setStep(3);setLoading(false)}
 function action(i:number,v:Preview['action']){setPreview(x=>x.map((r,n)=>n===i?{...r,action:v}:r))}
 async function saveDraft(){setLoading(true);const stats={total:preview.length,create:preview.filter(r=>r.action==='create').length,link:preview.filter(r=>r.action==='link').length,skip:preview.filter(r=>r.action==='skip').length,categories:preview.reduce((a:any,r)=>{a[r.category]=(a[r.category]||0)+1;return a},{})};const {data:batch,error}=await supabase.from('location_import_batches').insert({project_id:projectId,file_name:fileName,status:'draft',total_rows:stats.total,valid_rows:stats.create,duplicate_rows:stats.link,invalid_rows:stats.skip,summary:stats}).select('id').single();if(error||!batch){setLoading(false);return setMessage(error?.message||'تعذر إنشاء المسودة.')}const payload=preview.map(r=>({batch_id:batch.id,row_number:r.rowNumber,source_sheet:r.sheet,raw_data:r.raw,proposed_name:r.name,proposed_type:'location',proposed_category:r.category,normalized_name:r.normalized,matched_location_id:r.action==='link'?r.matched?.id:null,validation_status:r.status,decision:r.action,validation_notes:r.status==='similar'?['اسم مشابه ويحتاج مراجعة']:[]}));const {error:rowsError}=await supabase.from('location_import_rows').insert(payload);if(rowsError){setLoading(false);return setMessage(rowsError.message)}setDraftId(batch.id);setStep(4);setMessage('تم حفظ المسودة. لم تتم إضافة أي موقع للسجل بعد.');setLoading(false);await load()}
 async function approve(){if(!draftId)return;setLoading(true);const {data,error}=await supabase.rpc('approve_location_import_batch',{p_batch_id:draftId});if(error){setLoading(false);return setMessage(error.message)}setStep(5);setMessage(`تم الاعتماد: أضيف ${data.created||0} موقع، وربط ${data.linked||0} اسم، وتجاهل ${data.skipped||0} صف.`);setLoading(false);await load()}
 const summary=useMemo(()=>({total:preview.length,newRows:preview.filter(r=>r.status==='new').length,match:preview.filter(r=>r.status==='exact'||r.status==='similar').length,invalid:preview.filter(r=>r.status==='invalid').length}),[preview]);
 return <main className="platform-shell import-center" dir="rtl"><aside className="platform-sidebar"><div className="platform-brand-mark">م</div><div><strong>منصة الأعمال الميدانية</strong><span>السجل المركزي والاستيراد</span></div><nav><Link href="/platform">المشاريع</Link><Link href="/platform/locations">سجل المواقع المركزي</Link><Link className="active" href="/platform/imports">استيراد المواقع</Link><Link href="/platform/work-types">أنواع الأعمال</Link><Link href="/">النظام السابق</Link></nav></aside><section className="platform-content"><header className="platform-header"><div><span className="eyebrow">المرحلة الثالثة</span><h1>الاستيراد المرحلي للمواقع</h1><p>يقرأ عناوين التصنيفات داخل ملفاتكم تلقائيًا ثم يحفظ مسودة قبل الاعتماد النهائي.</p></div><Link className="secondary-action" href="/platform/locations">فتح السجل</Link></header>
 <div className="import-steps">{['المشروع والملف','تحليل التصنيفات','مراجعة القرارات','حفظ المسودة','الاعتماد'].map((l,i)=><div key={l} className={step>=i+1?'done':''}><b>{i+1}</b><span>{l}</span></div>)}</div>{message&&<div className={`import-message ${step===5?'success':''}`}>{message}</div>}
 {step===1&&<section className="platform-panel import-card"><div className="panel-heading"><div><h2>اختيار الملف</h2><p>يدعم الملفات ذات الأقسام: حدائق منسقة، تقليدية، زوائد، ميادين، شوارع، وزونات.</p></div></div><div className="form-grid"><label><span>المشروع</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">اختر المشروع</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="upload-box"><span>{loading?'جاري القراءة...':'اختيار ملف Excel'}</span><small>XLSX أو XLS أو CSV</small><input type="file" accept=".xlsx,.xls,.csv" disabled={!projectId||loading} onChange={handleFile}/></label></div></section>}
 {step===2&&<section className="platform-panel"><div className="panel-heading"><div><h2>نتيجة القراءة</h2><p>{fileName} · تم العثور على {source.length} موقع</p></div><button className="secondary-action" onClick={()=>setStep(1)}>تغيير الملف</button></div><div className="category-preview">{Object.entries(source.reduce((a:any,r)=>{a[r.category]=(a[r.category]||0)+1;return a},{})).map(([k,v])=><article key={k}><span>{k}</span><strong>{String(v)}</strong></article>)}</div><div className="import-actions"><button className="primary-action" onClick={analyze} disabled={loading}>{loading?'جاري التحليل...':'مراجعة المطابقات والتكرارات'}</button></div></section>}
 {step===3&&<><section className="platform-stats import-summary"><article><span>الإجمالي</span><strong>{summary.total}</strong></article><article><span>جديد</span><strong>{summary.newRows}</strong></article><article><span>مطابق / مشابه</span><strong>{summary.match}</strong></article><article><span>غير صالح</span><strong>{summary.invalid}</strong></article></section><section className="platform-panel"><div className="review-table-wrap"><table className="review-table"><thead><tr><th>الصف</th><th>الموقع</th><th>التصنيف</th><th>الحالة</th><th>المقترح</th><th>القرار</th></tr></thead><tbody>{preview.map((r,i)=><tr key={`${r.sheet}-${r.rowNumber}`}><td>{r.rowNumber}</td><td><strong>{r.name}</strong><small>{r.sheet}</small></td><td>{r.category}</td><td><span className={`review-badge ${r.status}`}>{r.status==='new'?'جديد':r.status==='exact'?'مطابق':r.status==='similar'?'متشابه':'غير صالح'}</span></td><td>{r.matched?.name||'—'}</td><td><select value={r.action} onChange={e=>action(i,e.target.value as Preview['action'])}><option value="create">موقع جديد</option><option value="link" disabled={!r.matched}>ربط بالموجود</option><option value="skip">تجاهل</option></select></td></tr>)}</tbody></table></div><div className="import-actions"><button className="secondary-action" onClick={()=>setStep(2)}>رجوع</button><button className="primary-action" onClick={saveDraft} disabled={loading}>{loading?'جاري الحفظ...':'حفظ كمسودة للمراجعة'}</button></div></section></>}
 {step===4&&<section className="platform-panel import-complete"><div className="complete-icon">✓</div><h2>المسودة جاهزة</h2><p>لم يُضف أي موقع بعد. الاعتماد التالي هو الذي ينقل المواقع إلى السجل المركزي.</p><div className="import-actions"><button className="primary-action" onClick={approve} disabled={loading}>{loading?'جاري الاعتماد...':'اعتماد الدفعة نهائيًا'}</button><button className="secondary-action" onClick={()=>setStep(3)}>العودة للمراجعة</button></div></section>}
 {step===5&&<section className="platform-panel import-complete"><div className="complete-icon">✓</div><h2>اكتمل الاستيراد</h2><p>{message}</p><div className="import-actions"><Link className="primary-action" href="/platform/locations">عرض المواقع</Link><button className="secondary-action" onClick={()=>{setStep(1);setSource([]);setPreview([]);setFileName('');setMessage('');setDraftId('')}}>ملف آخر</button></div></section>}
 <section className="platform-panel batches-panel"><div className="panel-heading"><div><h2>دفعات الاستيراد</h2><p>المسودات والمعتمدات محفوظة كسجل دائم.</p></div></div><div className="data-list">{batches.length?batches.map(b=><article key={b.id}><div><strong>{b.file_name}</strong><span>{b.projects?.name||'—'} · {new Date(b.created_at).toLocaleDateString('ar-SA')}</span></div><div className="batch-stats"><span>{b.total_rows} صف</span><span className={`pill ${b.status!=='approved'?'off':''}`}>{b.status==='approved'?'معتمد':b.status==='draft'?'مسودة':b.status}</span></div></article>):<div className="platform-empty">لا توجد دفعات بعد.</div>}</div></section></section></main>
}
